steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=europe-north1-docker.pkg.dev/${PROJECT_ID}/dataflow-pipeline-images/${_PIPELINE_NAME}:latest'
      - '--cache=true'
      - '--build-arg=PIPELINE_MODULE=${_PIPELINE_MODULE}'