name: Cloud Build and Flex Template Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering (hehe)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        create_credentials_file: true
        token_format: 'access_token'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.DATAFLOW_SERVICE_ACCOUNT }}

    - name: Verify Authentication
      run: gcloud auth list

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Kaniko settings
      run: |
        gcloud config set builds/use_kaniko True
        gcloud config set builds/kaniko_cache_ttl 480

    - name: Submit build to Cloud Build
      run: |
        gcloud builds submit --tag europe-north1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/solita-beam-demo:0.1.0 .
    - name: Build and upload Flex Template
      run: |
        gcloud dataflow flex-template build gs://totemic-dataflow-templates/templates/0.1.0/solita-beam-demo.json \
          --image europe-north1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/solita-beam-demo:0.1.0 \
          --sdk-language PYTHON \
          --metadata-file solita-beam-demo-metadata.json 
